---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: app-secret
spec:
  encryptedData:
    ADMIN_TOKEN: AgBwxpuTp3tEictxuho/gqJJXinSdmpJOpswsl+B/dWXz6pDNq0KxPGVZavABIHrKOeyotxCnBEcAxvYOLSMkk7bav8URT7BdXPGodgGTsMA4C83SHlrxDXqRoz85uLjfLPUOvyq16AxK7B3HVems9c3CU2RQKNqtcfFnCe/DvuznzzqgMPGLkJxCSk1Hbfd9Je26r3mYnbEYoBtx4/bCL0UWJNNHos+3ZWbRU9pkQWYs7erQuXZ7KQRMqImf71GIUmRvrM4akFcySXGpOx7VeOCzjcl72tD7K4uP0jmld0zRNYI0YR37bLn210yzzX+HqxjwlpcYNKCSbVqwT4WWs8LZzGTM9jPFaZ0xCPWxEPzfH3V/13lMxxhTBdBnkUBh275vrMQ/zEhFfbz0ZvESLQk7lOYnftBuI3qjvXoxRoytkujL8AdctlsOr9VT1kZnjctXfgIqENEQZVNvxUuVwF0uO4/tN7ly7NZt/1tvL35Lc/3IYHzQlmcwi49m3ElMsJT3SLSF5eHl5EbgLQMOad7jpWpTJrQsmxOWYw9f58Hsquh7xHNfTxaJyv4D6n564Tsa0QQUfFFbL+VKojpsgVh1zoI58yQdjzq0K/95WNuMp4i5V0wtxdUWDYn8PJw8LKhE6QqSHq+96TLerDNkeuDI1N3FA2UVa/7EfraQWc1ByY4oJ5IhQKinN2x6JPyeGdjWWjGAPpognW/DQJwT2A7z6aJw6gizOfA4BS0dt2AeMjAa0nT5gs7JaaN
    SECRET_KEY: AgAKUJa5cAgWTVrNZRhGd9OpeFsfG4HenjxwhT5oRiLyAi8S0m/UXj4CUfmFAKqXEJ7EAl4ljL5qlRfgCfyUxGGnMqmaakqj74VZhIamvrEej7rTuMHX/8IwbTrwGYXmpGH9GJL802j8uwq7JrIHNUABnb0ahI76rBAqYR0oeVCAj2NhkJIzMhLNid7y/QFs+2/t1Z5nGUyp+lMGLLJklier1bYGgD6EoDXo08GlASc9xr43QYitiJPafGe84vlpC24KemZoYWsI9opQW0FygfJOfu+h0rdsTUxJp8CpVP7cM9xRtT0HijFAe/Z6GMoKSU+l6L87jJPpcpE/C/oPMtYrAHW2s/h+J9LgDmGBdhYNNFfn2l3YhwCZhxhL0GKdQIKruOWiqnoA/0OxV3XHuTgTH71MuXH8H/lyjBfPRFkSJFQPgC4hwRsfiIcQyVVYEcmTTSi5+TnNGpuwo7LryfNuVMe/fcQQb/4mELjfhei3Kpe0Dq5iwgcjMxAiXP2g8lAOcbRv3gPRB4eMLb+URouJy/FLBSKOwLBRsQcOQX/8r9ShoITMabXxcOCcGbgNJY4e5M1FFuM2RVmE86+Jzdpg4OZoltQ7BTK54pmC6jqMkmkXTvMEt3Ym1qfWZATyheuWj/d2StTzUdafdabv1q90VZu+W1cI+WgFh2BNyozthbGV8gTR2PQmjPMMk+t3X7t/ZvuPm5a/IsAx28J84JfPFsDROGBMhqHOS8cq7gzCBg1Ts+F7Q9Bkmi0/aMGBPVRIdUx3E2b+Sk5SmHBNCVwR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: app-secret
